### PR TITLE
Add manual 7z.

### PR DESCRIPTION
**Pull request by HolographicWings**
That would be interesting to add a manual way to 7z releases instead of zip, especially when the 7z releases are 3x smaller.
I'm unsure if theses changes are correct, Shell is not my thing.
Do i have anything to fix ?

### CODE REVIEW

**Comment by vasilvestre** [comment]
I added to documentation the 7z type @HolographicWings

**Comment by HolographicWings** [comment]
oh sorry for the multiple commits, i forgot the PR and did some tests to fix an issue with my first commit.

**Comment by HolographicWings** [comment]
Well, that definitely don't work, the 7z creation work fine but the exclusions just don't work
I can't figure out how to fix that, i tried everything
For 7z, each exclusion must begin by -x!
for EXCLUSION in $INPUT_EXCLUSIONS don't split the exclusions
to made the 7z exclusions work, split them on every spaces is required

**Comment by TheDoctor0** [comment]
Hey @HolographicWings!
First and foremost thank you for this contribution.
I considered using `7z` initially instead of `zip` but the problem was that it was not available on Windows, so it did not fit the cross-platform availability requirement. That said, right now I don't see any harm in adding it as an alternative.

> for EXCLUSION in $INPUT_EXCLUSIONS don't split the exclusions from a long string to an array
> to made the 7z exclusions work, spliting them on every spaces is required

Actually, it `for EXCLUSION in $INPUT_EXCLUSIONS` does exactly that as Bash splits the string into words and skips the spaces between them when using a for loop.

**Comment by vasilvestre** [comment]
> Hey @HolographicWings! First and foremost thank you for this contribution. I considered using `7z` initially instead of `zip` but the problem was that it was not available on Windows, so it did not fit the cross-platform availability requirement. That said, right now I don't see any harm in adding it as an alternative.
> 
> > for EXCLUSION in $INPUT_EXCLUSIONS don't split the exclusions from a long string to an array
> > to made the 7z exclusions work, spliting them on every spaces is required
> 
> Actually, it `for EXCLUSION in $INPUT_EXCLUSIONS` does exactly that as Bash splits the string into words and skips the spaces between them when using a for loop.

FYI we managed to make zip and 7z, see here : https://github.com/HolographicWings/TOTK-Mods-collection/blob/main/.github/workflows/release.yml#L19

**Pull request merged**
